update the redis

diff --git a/.github/workflows/google-deploy.yml b/.github/workflows/google-deploy.yml
--- a/.github/workflows/google-deploy.yml
+++ b/.github/workflows/google-deploy.yml
@@ -52,6 +52,15 @@ jobs:
           
             # Navigate to the application directory
             cd fastapi
+            # Navigate to the application directory
+            cd /home/muhammad/fastapi
+          
+            # Verify the .env file
+            if [ ! -f .env ]; then
+              echo ".env file missing at /home/muhammad/fastapi/.env. Deployment aborted." && exit 1
+            else
+              echo ".env file found. Proceeding with deployment."
+            fi
           
             # Pull the latest code
             git fetch --all
